# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

courses = Array.new

course[0] = {"title" => "Authentic Leadership Development", "faculty" => "Perlow", "code" => "2090", "section" => "1", "day" => "TU", "time" => "11:40 AM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[1] = {"title" => "Authentic Leadership Development", "faculty" => "Perlow", "code" => "2090", "section" => "2", "day" => "TU", "time" => "01:15 PM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[2] = {"title" => "Authentic Leadership Development", "faculty" => "Gabarro", "code" => "2090", "section" => "3", "day" => "TH", "time" => "11:40 AM", "location" => "ALD 211", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[3] = {"title" => "Authentic Leadership Development", "faculty" => "Snook", "code" => "2090", "section" => "4", "day" => "TH", "time" => "01:15 PM", "location" => "ALD 211", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[4] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "van Bever", "code" => "1504", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "HAW 102", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[5] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Kaufman", "code" => "1504", "section" => "2", "day" => "X", "time" => "01:15 PM", "location" => "HAW 102", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[6] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Huber", "code" => "1504", "section" => "3", "day" => "Y", "time" => "10:05 AM", "location" => "ALD 210", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[7] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Huber", "code" => "1504", "section" => "4", "day" => "Y", "time" => "01:15 PM", "location" => "ALD 210", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[8] = {"title" => "Building Life Science Businesses", "faculty" => "Hamermesh", "code" => "1665", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "ALD 210", "quarter_credits" => "Q1,1.5", "term" => "Fall 2013", }
course[9] = {"title" => "Business Analysis and Valuation Using Financial Statements", "faculty" => "Healy;  Srinivasan", "code" => "1306", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[10] = {"title" => "Business Analysis and Valuation Using Financial Statements", "faculty" => "Healy;  Srinivasan", "code" => "1306", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[11] = {"title" => "Business at the Base of the Pyramid", "faculty" => "Rangan", "code" => "1908", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[12] = {"title" => "Business at the Base of the Pyramid", "faculty" => "Cole", "code" => "1908", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[13] = {"title" => "Consumer Marketing", "faculty" => "Gourville", "code" => "1940", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[14] = {"title" => "Consumer Marketing", "faculty" => "Keinan", "code" => "1940", "section" => "2", "day" => "X", "time" => "01:15 PM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[15] = {"title" => "Contemporary South Asia: Entrepreneurial Solutions to Intractable Social & Economic Problems", "faculty" => "Khanna", "code" => "1266", "section" => "0", "day" => "M", "time" => "03:30 PM", "location" => " Harvard University Cambridge campus", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[16] = {"title" => "Corporate Financial Management", "faculty" => "Luehrman", "code" => "1416", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[17] = {"title" => "Corporate Financial Management", "faculty" => "White", "code" => "1416", "section" => "2", "day" => "Y", "time" => "01:20 PM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[18] = {"title" => "Creating and Sustaining Competitive Advantage", "faculty" => "Van den Steen", "code" => "1285", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "ALD 208", "quarter_credits" => "Q1,1.5", "term" => "Fall 2013", }
course[19] = {"title" => "Creating Shared Value: Entrepreneurial and Corporate Models for a Changing Economy will not be offfered", "faculty" => "Marquis", "code" => " ", "section" => " ", "day" => " ", "time" => " ", "location" => " ", "quarter_credits" => " ", "term" => "Fall 2013", }
course[20] = {"title" => "Design Thinking and Innovation", "faculty" => "Datar", "code" => "1344", "section" => "1", "day" => "M", "time" => "03:30 PM", "location" => "BATT 122", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[21] = {"title" => "Design Thinking and Innovation", "faculty" => "Datar", "code" => "1344", "section" => "2", "day" => "M", "time" => "05:10 PM", "location" => "BATT 122", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[22] = {"title" => "Dynamic Markets", "faculty" => "Coval", "code" => "1407", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[23] = {"title" => "The Energy Business and Geopolitics", "faculty" => "Maurer", "code" => "1144", "section" => "1", "day" => "Y", "time" => "11:40 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[24] = {"title" => "The Energy Business and Geopolitics", "faculty" => "Maurer", "code" => "1144", "section" => "2", "day" => "Y", "time" => "01:15 PM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[25] = {"title" => "Entrepreneurial Finance", "faculty" => "Sahlman", "code" => "1624", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "ALD 208", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[26] = {"title" => "Entrepreneurial Finance", "faculty" => "Nanda", "code" => "1624", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "ALD 208", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[27] = {"title" => "Entrepreneurial Finance", "faculty" => "Nanda", "code" => "1624", "section" => "3", "day" => "Y", "time" => "11:40 AM", "location" => "ALD 208", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[28] = {"title" => "Entrepreneurship and Global Capitalism", "faculty" => "Jones", "code" => "1130", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "HAW 202", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[29] = {"title" => "Entrepreneurship and Global Capitalism", "faculty" => "Jones", "code" => "1130", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "HAW 202", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[30] = {"title" => "Entrepreneurship in Healthcare IT and Services", "faculty" => "Higgins", "code" => "1666", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "ALD 210", "quarter_credits" => "Q2,1.5", "term" => "Fall 2013", }
course[31] = {"title" => "Executing Strategy", "faculty" => "Harreld", "code" => "1263", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[32] = {"title" => "Executing Strategy", "faculty" => "Harreld", "code" => "1263", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[33] = {"title" => "Field Course: Business Marketing & Sales", "faculty" => "Cespedes", "code" => "6925", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "ALD 208", "quarter_credits" => "Q2,1.5", "term" => "Fall 2013", }
course[34] = {"title" => "Field Course: Commercializing Science", "faculty" => "Sato", "code" => "2107", "section" => "0", "day" => "W", "time" => "03:30 PM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[35] = {"title" => "Field Course: Health Care Computer Assisted Innovations", "faculty" => "Herzlinger", "code" => "6180", "section" => "0", "day" => "TU", "time" => "11:35 AM", "location" => "HAW 203", "quarter_credits" => "Q2,3", "term" => "Fall 2013", }
course[36] = {"title" => "Field Course: Innovating in Health Care", "faculty" => "Herzlinger", "code" => "6340", "section" => "0", "day" => "TU", "time" => "10:05 AM", "location" => "HAW 203", "quarter_credits" => "Q2,3", "term" => "Fall 2013", }
course[37] = {"title" => "Field Course: Innovation in Business, Energy, and Environment", "faculty" => "Lassiter;  Reinhardt;  Henderson;  Macomber; Toffel", "code" => "6611", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[38] = {"title" => "Field Course: Product Management 101", "faculty" => "Eisenmann", "code" => "6701", "section" => "0", "day" => "M", "time" => "05:30 PM", "location" => "HAW 203", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[39] = {"title" => "Financial Management of Smaller Firms", "faculty" => "Ruback;  Yudkoff", "code" => "1452", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[40] = {"title" => "Financial Management of Smaller Firms", "faculty" => "Ruback;  Yudkoff", "code" => "1452", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[41] = {"title" => "Financial Management of Smaller Firms", "faculty" => "Ruback;  Yudkoff", "code" => "1452", "section" => "3", "day" => "X", "time" => "11:40 AM", "location" => "HAW 101", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[42] = {"title" => "Founders' Dilemmas", "faculty" => "Wasserman", "code" => "1676", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "HAW 202", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[43] = {"title" => "Founders' Dilemmas", "faculty" => "Wasserman", "code" => "1676", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "HAW 202", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[44] = {"title" => "Fundamentals of Financial Reporting and Analysis will not be offered", "faculty" => "Hawkins", "code" => " ", "section" => " ", "day" => " ", "time" => " ", "location" => " ", "quarter_credits" => " ", "term" => "Fall 2013", }
course[45] = {"title" => "Games of Chance and Strategy will not be offered", "faculty" => "Kohlberg", "code" => " ", "section" => " ", "day" => " ", "time" => " ", "location" => " ", "quarter_credits" => " ", "term" => "Fall 2013", }
course[46] = {"title" => "Globalization and Emerging Markets", "faculty" => "Musacchio", "code" => "1151", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "ALD 208", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[47] = {"title" => "Globalization and Emerging Markets", "faculty" => "Musacchio", "code" => "1151", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "ALD 208", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[48] = {"title" => "History of American Democracy", "faculty" => "Moss", "code" => "1139", "section" => "0", "day" => "W", "time" => "03:30 PM", "location" => "ALD 207", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[49] = {"title" => "Innovating in Health Care Intensive Course", "faculty" => "Herzlinger", "code" => "2180", "section" => "0", "day" => "X", "time" => "10:05 AM", "location" => "HAW 203", "quarter_credits" => "Q1,3", "term" => "Fall 2013", }
course[50] = {"title" => "Innovation in Business, Energy, and Environment", "faculty" => "Lassiter;  Reinhardt;  Henderson;  Macomber; Toffel", "code" => "1165", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "HAW 201", "quarter_credits" => "Q1,1.5", "term" => "Fall 2013", }
course[51] = {"title" => "Investment Strategies", "faculty" => "Cohen;  Malloy", "code" => "1446", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "HAW 102", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[52] = {"title" => "Investment Strategies", "faculty" => "Cohen;  Malloy", "code" => "1446", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "HAW 102", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[53] = {"title" => "Leading the Global 1000", "faculty" => "Serafeim", "code" => "2013", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[54] = {"title" => "Legal Aspects of Entrepreneurship", "faculty" => "Goldberg", "code" => "1555", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "HAW 202", "quarter_credits" => "Q2,1.5", "term" => "Fall 2013", }
course[55] = {"title" => "Legal Aspects of Management", "faculty" => "Goldberg", "code" => "1545", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "HAW 202", "quarter_credits" => "Q1,1.5", "term" => "Fall 2013", }
course[56] = {"title" => "Managing International Trade and Investment", "faculty" => "Roscini", "code" => "1166", "section" => "1", "day" => "Y", "time" => "11:40 AM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[57] = {"title" => "Managing International Trade and Investment", "faculty" => "Roscini", "code" => "1166", "section" => "2", "day" => "Y", "time" => "01:15 PM", "location" => "HAW 201", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[58] = {"title" => "The Moral Leader", "faculty" => "Sucher", "code" => "1562", "section" => "1", "day" => "X", "time" => "01:15 PM", "location" => "HAW 203", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[59] = {"title" => "The Moral Leader", "faculty" => "Badaracco", "code" => "1562", "section" => "2", "day" => "Y", "time" => "01:15 PM", "location" => "HAW 202", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[60] = {"title" => "Negotiation", "faculty" => "Mohan", "code" => "2240", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "ALD 210", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[61] = {"title" => "Negotiation", "faculty" => "Luca", "code" => "2240", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "ALD 210", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[62] = {"title" => "Negotiation", "faculty" => "Mohan", "code" => "2240", "section" => "3", "day" => "X", "time" => "01:15 PM", "location" => "ALD 210", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[63] = {"title" => "Negotiation", "faculty" => "Wasynczuk", "code" => "2240", "section" => "4", "day" => "Y", "time" => "10:05 AM", "location" => "HAW 203", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[64] = {"title" => "Negotiation Intensive Course", "faculty" => "Gino", "code" => "2241", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "HAW 203", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[65] = {"title" => "The Online Economy: Strategy and Entrepreneurship", "faculty" => "Edelman", "code" => "1760", "section" => "1", "day" => "X", "time" => "11:40 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[66] = {"title" => "The Online Economy: Strategy and Entrepreneurship", "faculty" => "Edelman", "code" => "1760", "section" => "2", "day" => "X", "time" => "01:15 PM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[67] = {"title" => "Operations Strategy: Managing Growth", "faculty" => "Pisano", "code" => "2166", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "ALD 207", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[68] = {"title" => "Operations Strategy: Managing Growth", "faculty" => "Drake", "code" => "2166", "section" => "2", "day" => "Y", "time" => "01:15 PM", "location" => "ALD 207", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[69] = {"title" => "Private Equity Finance", "faculty" => "Ivashina", "code" => "1440", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "ALD 211", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[70] = {"title" => "Private Equity Finance", "faculty" => "Gompers", "code" => "1440", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "ALD 211", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[71] = {"title" => "Real Property", "faculty" => "Segel", "code" => "1684", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[72] = {"title" => "Real Property", "faculty" => "Segel", "code" => "1684", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[73] = {"title" => "Running a Federal Agency: Lessons from Business, Technology and Game Theory", "faculty" => "Genachowski", "code" => "1535", "section" => "0", "day" => "W", "time" => "05:00 PM", "location" => " Harvard Law School campus", "quarter_credits" => "Q1Q2,1.5", "term" => "Fall 2013", }
course[74] = {"title" => "Strategic Marketing in Creative Industries", "faculty" => "Elberse", "code" => "1914", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "ALD 207", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[75] = {"title" => "Strategic Marketing in Creative Industries", "faculty" => "Elberse", "code" => "1914", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "ALD 207", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[76] = {"title" => "Strategy and Technology", "faculty" => "Hagiu", "code" => "1286", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[77] = {"title" => "Strategy and Technology", "faculty" => "Hagiu", "code" => "1286", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "ALD 209", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[78] = {"title" => "Supply Chain Management", "faculty" => "Hammond", "code" => "2108", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "ALD 012", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[79] = {"title" => "Understanding Technology Businesses", "faculty" => "Shih", "code" => "2173", "section" => "0", "day" => "X", "time" => "08:30 AM", "location" => "ALD 211", "quarter_credits" => "Q1Q2,3", "term" => "Fall 2013", }
course[80] = {"title" => "Agribusiness", "faculty" => "Bell", "code" => "1915", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2013", }
course[81] = {"title" => "Authentic Leadership Development", "faculty" => "DeLong", "code" => "2090", "section" => "1", "day" => "TU", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2014", }
course[82] = {"title" => "Authentic Leadership Development", "faculty" => "DeLong", "code" => "2090", "section" => "2", "day" => "TU", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2015", }
course[83] = {"title" => "Authentic Leadership Development", "faculty" => "Snook", "code" => "2090", "section" => "3", "day" => "TH", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2016", }
course[84] = {"title" => "Authentic Leadership Development", "faculty" => "Snook", "code" => "2090", "section" => "4", "day" => "TH", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2017", }
course[85] = {"title" => "Behavioral and Value Investing", "faculty" => "Baker;  Greenwood", "code" => "1495", "section" => "0", "day" => "TH", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q3Q4,1.5", "term" => "Winter 2018", }
course[86] = {"title" => "The Board of Directors and Corporate Governance", "faculty" => "Lorsch", "code" => "2010", "section" => "0", "day" => "X", "time" => "01:10 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2019", }
course[87] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Shih", "code" => "1504", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2020", }
course[88] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Huber", "code" => "1504", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2021", }
course[89] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "Shih", "code" => "1504", "section" => "3", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2022", }
course[90] = {"title" => "Building and Sustaining a Successful Enterprise", "faculty" => "van Bever", "code" => "1504", "section" => "5", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2023", }
course[91] = {"title" => "Business at the Base of the Pyramid", "faculty" => "Chu", "code" => "1908", "section" => "0", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2024", }
course[92] = {"title" => "The Coming of Managerial Capitalism: The United States", "faculty" => "Nicholas", "code" => "1122", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2025", }
course[93] = {"title" => "The Coming of Managerial Capitalism: The United States", "faculty" => "Nicholas", "code" => "1122", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2026", }
course[94] = {"title" => "Competing Globally", "faculty" => "Alcacer", "code" => "1279", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2027", }
course[95] = {"title" => "Competing Globally", "faculty" => "Alcacer", "code" => "1279", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2028", }
course[96] = {"title" => "Competing with Social Networks", "faculty" => "Piskorski", "code" => "1217", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2029", }
course[97] = {"title" => "Competing with Social Networks", "faculty" => "Piskorski", "code" => "1217", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2030", }
course[98] = {"title" => "Corporate Strategy", "faculty" => "Collis", "code" => "1230", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2031", }
course[99] = {"title" => "Corporate Strategy", "faculty" => "Collis", "code" => "1230", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2032", }
course[100] = {"title" => "Creating the Modern Financial System", "faculty" => "Moss", "code" => "1160", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2033", }
course[101] = {"title" => "Creating Value Through Corporate Restructuring", "faculty" => "Gilson", "code" => "1420", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2034", }
course[102] = {"title" => "Creating Value Through Corporate Restructuring", "faculty" => "Gilson", "code" => "1420", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2035", }
course[103] = {"title" => "Creating Value Through Corporate Restructuring", "faculty" => "Mugford", "code" => "1420", "section" => "3", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2036", }
course[104] = {"title" => "Creative High-Impact Ventures: Entrepreneurs Who Changed the World", "faculty" => "Khaire", "code" => "1636", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2037", }
course[105] = {"title" => "Deals", "faculty" => "Mohan", "code" => "2267", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2038", }
course[106] = {"title" => "Designing Competitive Organizations", "faculty" => "Simons", "code" => "1373", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2039", }
course[107] = {"title" => "Designing Competitive Organizations", "faculty" => "Mikes", "code" => "1373", "section" => "2", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2040", }
course[108] = {"title" => "Digital Innovation and Transformation", "faculty" => "Lakhani", "code" => "2134", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2041", }
course[109] = {"title" => "Digital Innovation and Transformation", "faculty" => "Iansiti", "code" => "2134", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2042", }
course[110] = {"title" => "Digital Marketing Strategy", "faculty" => "Gupta", "code" => "1990", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2043", }
course[111] = {"title" => "Digital Marketing Strategy", "faculty" => "Teixeira", "code" => "1990", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2044", }
course[112] = {"title" => "Doing Business in China", "faculty" => "Kirby", "code" => "1575", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2045", }
course[113] = {"title" => "Enterprise Risk Management: Strategy and Leadership in the Face of Large-Scale Uncertainties", "faculty" => "Leonard", "code" => "1518", "section" => "0", "day" => "M", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2046", }
course[114] = {"title" => "Entrepreneurial Solutions for Market Failure", "faculty" => "Bower", "code" => "1585", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2047", }
course[115] = {"title" => "Entrepreneurship in Education Reform", "faculty" => "Kim", "code" => "1602", "section" => "0", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2048", }
course[116] = {"title" => "Field Course: Entrepreneurial Solutions to Market Failure", "faculty" => "Bower", "code" => "6580", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2049", }
course[117] = {"title" => "Field Course: Entrepreneurship through Acquisition", "faculty" => "Ruback;  Yudkoff", "code" => "6452", "section" => "0", "day" => "TH", "time" => "01:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2050", }
course[118] = {"title" => "Field Course: Housing in the United States", "faculty" => "Retsinas", "code" => "6462", "section" => "0", "day" => "TU", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2051", }
course[119] = {"title" => "Field Course: Impact Investing and Social Commercial Models", "faculty" => "Chu;  Cole", "code" => "6908", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2052", }
course[120] = {"title" => "Field Course: Launching Technology Ventures", "faculty" => "Eisenmann", "code" => "6750", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2053", }
course[121] = {"title" => "Field Course: Planning Your Business in China", "faculty" => "Kirby", "code" => "6575", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2054", }
course[122] = {"title" => "Field Course: Stock Pitching", "faculty" => "Cohen", "code" => "6446", "section" => "0", "day" => "M", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2055", }
course[123] = {"title" => "General Management: Processes and Action", "faculty" => "Garvin", "code" => "1556", "section" => "1", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2056", }
course[124] = {"title" => "General Management: Processes and Action", "faculty" => "Garvin", "code" => "1556", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2057", }
course[125] = {"title" => "Global Strategic Management", "faculty" => "Siegel", "code" => "1534", "section" => "0", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2058", }
course[126] = {"title" => "Great Negotiators", "faculty" => "Sebenius", "code" => "2215", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2059", }
course[127] = {"title" => "High Performance Collaboration in a Global Economy", "faculty" => "Neeley", "code" => "2020", "section" => "0", "day" => "Y", "time" => "01:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2060", }
course[128] = {"title" => "How Star Women Succeed: Leading Effective Careers and Organizations", "faculty" => "Groysberg", "code" => "2062", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2061", }
course[129] = {"title" => "I-LAB Course: Cultural Entrepreneurship in New York City", "faculty" => "Eisenmann", "code" => "6075", "section" => "0", "day" => " ", "time" => " ", "location" => "", "quarter_credits" => "J,1.5", "term" => "Winter 2062", }
course[130] = {"title" => "I-LAB Course: Design Thinking", "faculty" => "Datar", "code" => "6085", "section" => "0", "day" => "W", "time" => "06:45 PM", "location" => "", "quarter_credits" => "J,1.5", "term" => "Winter 2063", }
course[131] = {"title" => "Institutions, Macroeconomics and the Global Economy", "faculty" => "Di Tella", "code" => "1180", "section" => "1", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2064", }
course[132] = {"title" => "Institutions, Macroeconomics and the Global Economy", "faculty" => "Di Tella", "code" => "1180", "section" => "2", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2065", }
course[133] = {"title" => "Institutions, Macroeconomics and the Global Economy", "faculty" => "Iyer", "code" => "1180", "section" => "3", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2066", }
course[134] = {"title" => "Introduction to Tax Decisions by Individuals and Companies", "faculty" => "Pozen", "code" => "1488", "section" => "0", "day" => "X", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2067", }
course[135] = {"title" => "IXP Course: China; Current Challenges, Future Opportunities", "faculty" => "Marquis", "code" => "6045", "section" => "1", "day" => "W", "time" => "06:45 PM", "location" => "", "quarter_credits" => "J,1.5", "term" => "Winter 2068", }
course[136] = {"title" => "IXP Course: China; Current Challenges, Future Opportunities", "faculty" => "Kirby", "code" => "6045", "section" => "2", "day" => "W", "time" => "06:45 PM", "location" => "", "quarter_credits" => "J,1.5", "term" => "Winter 2069", }
course[137] = {"title" => "IXP Course: Competing with Social Networks - California", "faculty" => "Piskorski", "code" => "6017", "section" => "0", "day" => "F", "time" => "03:30 PM", "location" => "", "quarter_credits" => "J,3", "term" => "Winter 2070", }
course[138] = {"title" => "IXP Course: Japan; Innovating for Recovery: Business Strategy and Entrepreneurship", "faculty" => "Takeuchi", "code" => "6062", "section" => "0", "day" => "W", "time" => "06:45 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2071", }
course[139] = {"title" => "Knowledge-Based Strategy", "faculty" => "Takeuchi", "code" => "1215", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2072", }
course[140] = {"title" => "Launching Global Ventures", "faculty" => "Kerr", "code" => "1627", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2073", }
course[141] = {"title" => "Launching Technology Ventures", "faculty" => "Eisenmann", "code" => "1755", "section" => "1", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2074", }
course[142] = {"title" => "Launching Technology Ventures", "faculty" => "Bussgang", "code" => "1755", "section" => "2", "day" => "X", "time" => "01:45 PM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2075", }
course[143] = {"title" => "Leading Professional Service Firms", "faculty" => "Eccles;  Gardner", "code" => "1770", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2076", }
course[144] = {"title" => "Managing Global Health: Applying Behavioral Economics to Create Impact", "faculty" => "Ashraf", "code" => "2230", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2077", }
course[145] = {"title" => "Managing Service Operations", "faculty" => "Tucker", "code" => "2120", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2078", }
course[146] = {"title" => "Managing Service Operations", "faculty" => "Tucker", "code" => "2120", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2079", }
course[147] = {"title" => "Managing Social Enterprise", "faculty" => "Ebrahim", "code" => "1582", "section" => "0", "day" => "TU", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2080", }
course[148] = {"title" => "Managing the Financial Firm", "faculty" => "Scharfstein", "code" => "1509", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2081", }
course[149] = {"title" => "Managing, Organizing & Motivating for Value", "faculty" => "Wasynczuk", "code" => "1816", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2082", }
course[150] = {"title" => "Managing, Organizing & Motivating for Value", "faculty" => "Hall", "code" => "1816", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2083", }
course[151] = {"title" => "Negotiation", "faculty" => "Brooks", "code" => "2240", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2084", }
course[152] = {"title" => "Negotiation", "faculty" => "Beshears", "code" => "2240", "section" => "2", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2085", }
course[153] = {"title" => "Negotiation Intensive Course", "faculty" => "Sebenius", "code" => "2241", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2086", }
course[154] = {"title" => "Power and Glory in Turbulent Times: The History of Leadership from Henry V to Steve Jobs", "faculty" => "Koehn", "code" => "1123", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2087", }
course[155] = {"title" => "Power and Glory in Turbulent Times: The History of Leadership from Henry V to Steve Jobs", "faculty" => "Koehn", "code" => "1123", "section" => "2", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2088", }
course[156] = {"title" => "Real Asset Finance", "faculty" => "Perold", "code" => "1475", "section" => "0", "day" => "TH", "time" => "03:30 PM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2089", }
course[157] = {"title" => "Real Estate in Frontier Markets", "faculty" => "Retsinas", "code" => "1405", "section" => "0", "day" => "X", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2090", }
course[158] = {"title" => "Real Estate Private Equity", "faculty" => "Lietz", "code" => "1484", "section" => "0", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2091", }
course[159] = {"title" => "Reimagining Capitalism", "faculty" => "Henderson", "code" => "1524", "section" => "1", "day" => "X", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2092", }
course[160] = {"title" => "Reimagining Capitalism", "faculty" => "Rose", "code" => "1524", "section" => "2", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2093", }
course[161] = {"title" => "Reimagining Capitalism", "faculty" => "Henderson", "code" => "1524", "section" => "3", "day" => "X", "time" => "01:30 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2094", }
course[162] = {"title" => "Retailing", "faculty" => "Alvarez", "code" => "1952", "section" => "0", "day" => "Y", "time" => "08:30 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2095", }
course[163] = {"title" => "The Role of Government in Market Economies", "faculty" => "Weinzierl", "code" => "1195", "section" => "0", "day" => "Y", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2096", }
course[164] = {"title" => "Sustainable Cities: Finance, Design, and Innovation", "faculty" => "Macomber", "code" => "1487", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2097", }
course[165] = {"title" => "Understanding and Influencing Operations as an Investor", "faculty" => "Raman", "code" => "2135", "section" => "0", "day" => "X", "time" => "01:15 PM", "location" => "", "quarter_credits" => "Q3,1.5", "term" => "Winter 2098", }
course[166] = {"title" => "Venture Capital and Private Equity", "faculty" => "Rhodes-Kropf", "code" => "1428", "section" => "1", "day" => "Y", "time" => "10:05 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2099", }
course[167] = {"title" => "Venture Capital and Private Equity", "faculty" => "Rhodes-Kropf", "code" => "1428", "section" => "2", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q3Q4,3", "term" => "Winter 2100", }
course[168] = {"title" => "Venture Capital in Historical Perspective", "faculty" => "Hardymon;  Nicholas", "code" => "1125", "section" => "0", "day" => "Y", "time" => "11:40 AM", "location" => "", "quarter_credits" => "Q4,1.5", "term" => "Winter 2101", }

courses.each do |course|
  course_entry = Course.new()
  course_entry.title = course['title']
  course_entry.faculty = course['faculty']
  course_entry.code = course['code']
  course_entry.section = course['section']
  course_entry.day = course['day']
  course_entry.time = course['time']
  course_entry.location = course['location']
  course_entry.quarter_credits = course['quarter_credits']
  course_entry.term = course['term']

  course_entry.save()

end